### ISSUE TITLE
Apk?

### ISSUE THREAD

**Issue by JimLynchCodes** [learnseleniumtesting/AppiumTestApp#1]
Hi. I'm trying to test this project with Appium. Is there an apk file with this project that I should be using? :)

Thanks.

**Comment by codeandqa** [comment]
@JimTheMan Will this work?
http://learnseleniumtesting.com/download/testapp_apk/

**Comment by JimLynchCodes** [comment]
I think it should, but I actually never got it to work. lol

**Comment by codeandqa** [comment]
@JimTheMan  Sorry for that. By any chance did you try http://ionicframework.com/getting-started/?

**Comment by JimLynchCodes** [comment]
Thanks @learnseleniumtesting , but that's just an ionic getting started guide. How would that help me for testing an app with Appium? Lol

**Comment by codeandqa** [comment]
@JimTheMan  I thought you have seen this: http://learnseleniumtesting.com/tutorials/app-testing-using-appium-webdriver/
